language: android
jdk: oraclejdk8
group: deprecated-2017Q4
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.3
  - extra
  - android-25
  - android-17
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
before_install:
  # accept licenses
  # https://stackoverflow.com/questions/37615379/travis-ci-build-doesnt-work-with-android-constraint-layout
  - yes | sdkmanager "build-tools;28.0.3" "platforms;android-28"
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
script:
  - "./gradlew build"
  - "./gradlew packageDebugAndroidTest"
before_deploy:
  - mv app/build/outputs/apk/app-debug.apk app/build/outputs/apk/app-uiautomator.apk
  - mv app/build/outputs/apk/app-debug-androidTest.apk app/build/outputs/apk/app-uiautomator-test.apk
deploy:
  provider: releases
  api_key:
    secure: o4BSXTbUReVcjz9axByXK6mHzyZAj63wSO7MYZ9+7PTIVGS2SOi/C11sD5EgptWT6CHFSOepEb0BGvRd8EM6j6cr+sMs/UUy4e1l/ujpLZxpVSwkvYZjrmxy3cjwShLGecfgIwgf6+dGC42/nAtT5Iz1lPHuMzdHJSt8GnLgNFo8gz+/R0c/AAxqiK0l9/w68FLkSSSSL3PnFEdSLu374VnHrkPChcdhzrJ7vbIKyS9c1mq12Ze2W+FUq7ACx+b+IQqInda9cI3RtITxV0DUHNmte7GwHOJBdGUqUQUALbEWCXYWvfsKVz4A92Gqt+mFbnQacQaPIIqoFn8yJ3KZlKrpv8UnCSvHsr0Ic27IsVSI8lI7ifdGiUZKqOfJeT2ogOKDe19Hb2ksmIuS1Wdu9VtJWycXJJChD5Xr5AaCLd7biMiPFsBQVOcAx9+6DqtxgPCkvoTmafQdDeHaBx8lvJZ5aCpnWKo8HvLXcg3/Dxr25S0YFblynUtMU5zoqivQGzc4ZFWbBngFxbmXvr4aEnufT+usoDC1A63SEPW2V6WIHviPSTVrxOqrghXL+olNcb1KyS4VMDGVFHqwXUpE0TUyMlISKzWw0IglGuQMaSm1Vr2PIwBW5nCqDUQAaMZpjWbMBvfSSkZCR5gUSWx/Z50cQlsgFEMQtV3KuryD+KU=
  file:
    - app/build/outputs/apk/app-uiautomator.apk
    - app/build/outputs/apk/app-uiautomator-test.apk
  skip_cleanup: true
  on:
    repo: openatx/android-uiautomator-server
    tags: true
